version: '3.4'

services:
  primesgenerator:
    image: ${DOCKER_REGISTRY-}primesgenerator
    build:
      context: .
      dockerfile: PrimesGenerator/Dockerfile
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9101:9101"
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '5myIYRO1gyeVX3YIhNrdYe'

  clickhouse:
    build: 
      context: .
      dockerfile: ClickHouse/Dockerfile
    depends_on:
      - kafka
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "18123:8123"
      - "19000:9000"
    environment:
        CLICKHOUSE_DB: alfn 
        CLICKHOUSE_USER: alfn
        CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1 
        CLICKHOUSE_PASSWORD: alfn



